export const MODERATION_REQUEST_QUEUE = 'MODERATION_REQUEST';

export const MODERATION_NOTIFY_QUEUE = 'MODERATION_NOTIFY';

export const REVIEW_REQUEST_QUEUE = 'REVIEW_REQUEST';

export const REVIEW_NOTIFY_QUEUE = 'REVIEW_NOTIFY';
